### ISSUE TITLE
AttributeError: 'Backend' object has no attribute 'activate_builtin_random'

### ISSUE THREAD

**Issue by bjorn3** [internetarchive/warcprox#196]
```
Traceback (most recent call last):
  File "/home/bjorn/Documenten/crawler/.env/bin/warcprox", line 33, in <module>
    sys.exit(load_entry_point('warcprox==2.4.17', 'console_scripts', 'warcprox')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjorn/Documenten/crawler/.env/lib/python3.11/site-packages/warcprox/main.py", line 316, in main
    cryptography.hazmat.backends.openssl.backend.activate_builtin_random()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Backend' object has no attribute 'activate_builtin_random'
```

This method was dropped in https://github.com/pyca/cryptography/commit/5e6476a4c6e094926a983dcf5cbe9488c30aeb53 which was released in cryptography 41.0.0.

**Comment by FHantke** [comment]
Do you have any workaround for the moment?

**Comment by FHantke** [comment]
Seems to work with the current version: `pip install git+https://github.com/internetarchive/warcprox.git
`

**Comment by bjorn3** [comment]
The workaround I did was to force cryptography version 40 to be used.
