### ISSUE TITLE
ImportError: No module named controller

### ISSUE THREAD

**Issue by ethus3h** [internetarchive/warcprox#23]
So, it's totally possible that this is an installation or configuration problem on my part, but I'm not sure what it would be:

```
$ warcprox
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/warcprox", line 11, in <module>
    load_entry_point('warcprox==2.0.1', 'console_scripts', 'warcprox')()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2627, in load_entry_point
    return ep.load()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2287, in load
    return self.resolve()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2293, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python2.7/site-packages/warcprox/__init__.py", line 131, in <module>
    import warcprox.controller as controller
ImportError: No module named controller
```

Any thoughts? Thanks!

**Comment by nlevitt** [comment]
I don't know... does /usr/lib64/python2.7/site-packages/warcprox/controller.py exist? How did you install warcprox?

**Comment by ethus3h** [comment]
Yup, it does! (I installed using it using Portage, the package manager for the operating system I use.)

```
kyan@elegiac /usr/lib64/python2.7/site-packages/warcprox nohup compiz --replace openbox $ ls
bigtable.py     dedup.pyc        __init__.pyo   mitmproxy.py   stats.pyc      warcproxy.pyo   writer.pyc
bigtable.pyc    dedup.pyo        kafkafeed.py   mitmproxy.pyc  stats.pyo      warc.py         writer.pyo
bigtable.pyo    dump_anydbm.py   kafkafeed.pyc  mitmproxy.pyo  version.txt    warc.pyc        writerthread.py
controller.py   dump_anydbm.pyc  kafkafeed.pyo  playback.py    warcprox.py    warc.pyo        writerthread.pyc
controller.pyc  dump_anydbm.pyo  main.py        playback.pyc   warcprox.pyc   warcwriter.py   writerthread.pyo
controller.pyo  __init__.py      main.pyc       playback.pyo   warcproxy.py   warcwriter.pyc
dedup.py        __init__.pyc     main.pyo       stats.py       warcproxy.pyc  writer.py
kyan@elegiac /usr/lib64/python2.7/site-packages/warcprox nohup compiz --replace openbox $ 
```

**Comment by ethus3h** [comment]
(I don't know if it means anything to you, but Portage installs packages using recipes called "ebuilds"; here's the one I created for warcprox: https://github.com/ethus3h/wreathe-overlay/blob/master/dev-python/warcprox/warcprox-2.0.1.ebuild)

**Comment by nlevitt** [comment]
I don't know. Seems like something that gentoo python experts can help you with. Sorry!

**Comment by ethus3h** [comment]
Ah, gotcha. Sorry to bother you. Thanks! :)

**Comment by nlevitt** [comment]
No problem, if you find the solution, please post it here for the next person. :)
