### ISSUE TITLE
__init__() got multiple values for argument 'ca_name'

### ISSUE THREAD

**Issue by fkneist** [internetarchive/warcprox#26]
hi,

I installed warcprox 2.0.1  (on Ubuntu 17.04, Python 3.5.3, pip 9.0.1) and got the following error when running `$ warcprox`:

`2017-05-25 22:39:34,521 20773 INFO MainThread warcprox.dedup.DedupDb.__init__(dedup.py:46) creating new deduplication database ./warcprox-dedup.db
2017-05-25 22:39:34,567 20773 INFO MainThread warcprox.stats.StatsDb.__init__(stats.py:67) creating new stats database ./warcprox-stats.db
Traceback (most recent call last):
  File "/usr/local/bin/warcprox", line 11, in <module>
    sys.exit(main())
  File "/home/student/.local/lib/python3.5/site-packages/warcprox/main.py", line 256, in main
    real_main(args)
  File "/home/student/.local/lib/python3.5/site-packages/warcprox/main.py", line 222, in real_main
    controller = init_controller(args)
  File "/home/student/.local/lib/python3.5/site-packages/warcprox/main.py", line 186, in init_controller
    ca_name=ca_name)
TypeError: __init__() got multiple values for argument 'ca_name'`

To install it globally, in order to use it from the command line I typed:
`$ sudo -H pip3 install warcprox`

Did I miss something?

**Comment by nlevitt** [comment]
Ah shoot, there was a breaking api change in certauth 1.2 and warcprox 2.0.1 specifies `certauth>=1.1.0` as the dependency. You should be able to fix by running `pip install certauth<1.2` or similar.

**Comment by fkneist** [comment]
thank you!
for the record: `$ sudo pip3 install "certauth<1.2"` solved the issue.

**Comment by nlevitt** [comment]
Oh, good. Resolving since won't be an issue in the next release.
