### ISSUE TITLE
"ImportError: No module named 'resource'"

### ISSUE THREAD

**Issue by DoomTay** [internetarchive/warcprox#27]
Attempting to run this on a Windows build with something as simple as just "warcprox" in the command line yields this error

```
Traceback (most recent call last):
  File "C:\Users\Taylor\AppData\Local\Programs\Python\Python35-32\Scripts\warcprox-script.py", line 11, in <module>
    load_entry_point('warcprox==2.0.1', 'console_scripts', 'warcprox')()
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 2642, in load_entry_point
    return ep.load()
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 2296, in load
    return self.resolve()
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 2302, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\warcprox\__init__.py", line 132, in <module>
    import warcprox.playback as playback
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\warcprox\playback.py", line 41, in <module>
    from warcprox.mitmproxy import MitmProxyHandler
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\warcprox\mitmproxy.py", line 55, in <module>
    import resource
ImportError: No module named 'resource'
```

Is it because I don't have libffi-dev or libssl-dev, and this being a Windows machine, I don't know how to get them?

**Comment by nlevitt** [comment]
Ok thanks github for cl

**Comment by nlevitt** [comment]
Please reopen if still a problem

**Comment by DoomTay** [comment]
As of version 2.1b1.dev96, here is still technically a different error, but I still see a reference to "No module named 'resource'"

```
2017-09-05 16:11:41,557 11316 WARNING MainThread warcprox.warcproxy.WarcProxy.__init__(mitmproxy.py:456) unable to calculate optimal number of threads based on resource limits due to No module named 'resource'
2017-09-05 16:11:41,558 11316 INFO MainThread warcprox.warcproxy.WarcProxy.__init__(mitmproxy.py:458) max_threads=100
2017-09-05 16:11:41,567 11316 INFO MainThread warcprox.warcproxy.WarcProxy.server_activate(warcproxy.py:405) listening on 127.0.0.1:8000
Traceback (most recent call last):
  File "C:\Users\Taylor\AppData\Local\Programs\Python\Python35-32\Scripts\warcprox-script.py", line 11, in <module>
    load_entry_point('warcprox==2.1b1.dev96', 'console_scripts', 'warcprox')()
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\warcprox\main.py", line 288, in main
    real_main(args)
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\warcprox\main.py", line 254, in real_main
    signal.signal(signal.SIGQUIT, dump_state)
AttributeError: module 'signal' has no attribute 'SIGQUIT'
```

**Comment by nlevitt** [comment]
> As of version 2.1b1.dev96, here is still technically a different error, but I still see a reference to "No module named 'resource'"

Yeah, that's just a warning, the sensible thing to do in that case.

b89f834ce37a2b317e55d0517934dcd49137b5ae should address the SIGQUIT issue.
