### ISSUE TITLE
Signature change for `certauth.certauth.CertificateAuthority()`

### ISSUE THREAD

**Issue by jeffcasavant** [internetarchive/warcprox#42]
`CertificateAuthority()` seems to take one less positional argument than when version 2.0.1 came out, thus the version of WarcProx installed by pip does not work currently.  Confirmed in 3.6 and 2.7.  Dev version of WarcProx does not have this problem.

```
2017-10-26 11:49:58,004 32031 INFO MainThread warcprox.dedup.DedupDb.__init__(dedup.py:46) creating new deduplication database ./warcprox-dedup.db
2017-10-26 11:49:58,008 32031 INFO MainThread warcprox.stats.StatsDb.__init__(stats.py:67) creating new stats database ./warcprox-stats.db
Traceback (most recent call last):
  File "/usr/bin/warcprox", line 11, in <module>
    load_entry_point('warcprox==2.0.1', 'console_scripts', 'warcprox')()
  File "/usr/lib/python3.6/site-packages/warcprox/main.py", line 256, in main
    real_main(args)
  File "/usr/lib/python3.6/site-packages/warcprox/main.py", line 222, in real_main
    controller = init_controller(args)
  File "/usr/lib/python3.6/site-packages/warcprox/main.py", line 186, in init_controller
    ca_name=ca_name)
TypeError: __init__() got multiple values for argument 'ca_name'
```

**Comment by nlevitt** [comment]
I pushed a new release (2.2) to pypi, which should address this issue.
